name: ansible to do configuration management

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ls -l

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Check Ansible version
        run: ansible --version
        
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory playbook.yml --private-key private_key.pem